---
# tasks file for artifactory-ansible-role

- include: validate-java.yml
- include: verify-installation.yml
- include: install-{{ artifactory_flavor }}.yml

#- include: configure-{{ artifactory_database_engine }}.yml

- name: Resigter Artifactory-{{ artifactory_flavor }}
  service: name=artifactory state=started



